name: Geph4 Self Hosting
on: 
  #push:
  workflow_dispatch:
  schedule:
    - cron: '1 1 1 * *'

#jobs 下面的 job1，job2 默认是独立进行的，提高效率.如需先后用need
jobs:


  Build-geph4-client:
    runs-on: ubuntu-latest
    steps:
    - name: install geph4-client
      run: cargo install --locked geph4-client  
    - run: |
        ls ~/.cargo/bin
        cp ~/.cargo/bin/geph4-client .
    - name: upload-artifact geph4-client
      uses: actions/upload-artifact@v2
      with:
        name: geph4-client
        path: ~/.cargo/bin/geph4-client
  


  Build-geph4-exit: 
    runs-on: ubuntu-latest
    steps:
    
    - name: install geph4-exit
      run: cargo install --locked geph4-exit
    
    - run: |
        ls ~/.cargo/bin
        cp ~/.cargo/bin/geph4-exit .
    
    - name: upload-artifact geph4-exit
      uses: actions/upload-artifact@v2
      with:
        name: geph4-exit
        path: ~/.cargo/bin/geph4-exit
    

  Copying-files-to-VPS:
    runs-on: ubuntu-latest
    needs: [Build-geph4-client, Build-geph4-exit]
    steps:
    
    - uses: actions/download-artifact@v2
    - run: |
        mkdir geph
        mv geph4-exit/geph4-exit geph/
        mv geph4-client/geph4-client geph/
    - run: ls -R

    - name: copying files to VPS
      uses: appleboy/scp-action@master
      with: 
        host: ${{ secrets.SJ_HOST }}
        username: ${{ secrets.SJ_USER }}
        #password: ${{ secrets.SJ_PASSWORD }}
        key: ${{ secrets.SJ_KEY }}
        source: "geph"
        target: "vps/docker-geph4-exit-self/app"
        strip_components: 1

    - name: Remote Commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SJ_HOST }}
        username: ${{ secrets.SJ_USER }}
        #password: ${{ secrets.SJ_PASSWORD }}
        key: ${{ secrets.SJ_KEY }}
        script_stop: true  ##第一次失败后停止脚本
        script: |
          cd vps/docker-geph4-exit-self
          chmod +x app/geph4-client app/geph4-exit
          docker-compose restart