name: Geph4 Self Hosting
on: 
  #push:
  workflow_dispatch:
  schedule:
    - cron: '1 1 1 * *'

#jobs 下面的 job1，job2 默认是独立进行的，提高效率.如需先后用need
jobs:
  Build-geph4-client:
    runs-on: ubuntu-latest
    steps:
    - name: install geph4-client
      run: cargo install --locked geph4-client
    - run: ls ~/.cargo/bin
    - name: UP geph4-client
      uses: actions/upload-artifact@v2
      with:
        name: geph4-client
        path: ~/.cargo/bin/geph4-client
    
    - run: |
        echo "ls ~ client"
        ls



  Build-geph4-exit: 
    runs-on: ubuntu-latest
    steps:
    
    - name: install geph4-exit
      run: cargo install --locked geph4-exit
    
    - run: |
        ls ~/.cargo/bin
        cp ~/.cargo/bin/geph4-exit .
    
    - name: UP geph4-exit
      uses: actions/upload-artifact@v2
      with:
        name: geph4-exit
        path: ~/.cargo/bin/geph4-exit
    
    - name: copying files
      uses: appleboy/scp-action@master
      with: 
        host: ${{ secrets.SJ_HOST }}
        username: ${{ secrets.SJ_USER }}
        password: ${{ secrets.SJ_PASSWORD }}
        source: "geph4-exit"
        target: "vps/docker-geph4-exit-self/app"
#        strip_components: 1

    - name: Remote Commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SJ_HOST }}
        username: ${{ secrets.SJ_USER }}
        password: ${{ secrets.SJ_PASSWORD }}
        script_stop: true  ##第一次失败后停止脚本
        script: |
          cd vps/docker-geph4-exit-self
          sudo docker-compose restart

    - run: |
        echo "ls ~ exit"
        ls