name: download artifact
on: 
  push:
  workflow_dispatch:
  #schedule:
  #  - cron: '1 1 1 * *'

jobs:
  downartifact:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      with: 
        name: mytest
    
    - name:display
      run: ls -R
