name: download artifact
on: 
  push:
  workflow_dispatch:
  #schedule:
  #  - cron: '1 1 1 * *'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - run: pwd
    - uses: actions/checkout@main
    - run: pwd