name: ssh to sj
on: 
  push:
  workflow_dispatch:
  #schedule:
  #  - cron: '1 1 1 * *'

jobs:
  sshdeploy:
    runs-on: ubuntu-latest
    steps:
    - run: |
        cd ~
        pwd
        echo hell1122 > sshtest.txt
        cat sshtest.txt
        
    - name: ls -a via ssh
      uses: fifsky/ssh-action@master
      with:
        command: |
          cd /tmp
          ls -a
        host: ${{ secrets.SJ_HOST }}
        user: ${{ secrets.SJ_USER }}
        pass: ${{ secrets.SJ_PASSWORD}}

        
