name: ssh to sj
on: 
  push:
  workflow_dispatch:
  #schedule:
  #  - cron: '1 1 1 * *'

jobs:
  sshdeploy:
    runs-on: ubuntu-latest
    steps:
    - run: |
        cd ~
        pwd
        echo hell1122 > sshtest.txt
        cat sshtest.txt
        
    - name: ssh
      uses: Creepios/sftp-action@v1.0.1
      with:
        host: ${{ secrets.SJ_HOST }}
        port: 22
        username: ${{ secrets.SJ_USER }}
        password: ${{ secrets.SJ_PASSWORD }}
        localPath: '/home/runner/sshtest.txt'
        remotePath: '/root/'

    - name: ls -a via ssh
      uses: fifsky/ssh-action@master
      with:
        command: |
          cd /root
          cat sshtest.txt
        host: ${{ secrets.SJ_HOST }}
        user: ${{ secrets.SJ_USER }}
        pass: ${{ secrets.SJ_PASSWORD}}    

        
