name: ssh to sj
on: 
  push:
  workflow_dispatch:
  #schedule:
  #  - cron: '1 1 1 * *'

jobs:
  sshdeploy:
    runs-on: ubuntu-latest
    steps:
    - run: |
        cd ~
        pwd
        echo hell1122 > sshtest.txt
        cat sshtest.txt
        
    - uses: hengkx/ssh-deploy@v1.0.1
      env:
        HOST: direct.labs.play-with-docker.com
        USERNAME: ip172-18-0-59-c4qph6vnjsv000aaijmg
        PASSWORD: 
        PORT: 22
        SOURCE: ~/sshtest.txt
        TARGET: /root
        AFTER_COMMAND: 'cat /root/sshtest.txt'

        
