name: ssh to sj
on: 
  push:
  workflow_dispatch:
  #schedule:
  #  - cron: '1 1 1 * *'

jobs:
  sshdeploy:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo sshtest112233 > /home/sshtest.txt
        cat /home/sshtest.txt


        
