name: test
on: 
  push:
  workflow_dispatch:
  #schedule:
  #  - cron: '1 1 1 * *'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - run: pwd
    - run: |
        git https://github.com/geph-official/geph4.git
        ls 
        cd geph4
        ls
        #cargo build --release --locked --manifest-path=geph4-client/Cargo.toml
        #cargo build --release --locked --manifest-path=geph4-vpn-helper/Cargo.toml
        ls
        #ls bin