name: test
on: 
  push:
  workflow_dispatch:
  #schedule:
  #  - cron: '1 1 1 * *'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - run: pwd
    - run: |
        git clone https://github.com/geph-official/geph4.git
        ls 
        cd geph4
        cargo build --release --locked --manifest-path=Cargo.toml
        cargo build --release --locked --manifest-path=Cargo.toml
        echo "---------ls ---------------"
        ls
        echo "---------ls bin-----------"
        ls bin