name: copying files && Remote Commands via SSH
on: 
  push:
  workflow_dispatch:
  #schedule:
  #  - cron: '1 1 1 * *'

jobs:
  sshdeploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: creat file
      run: |
        echo aaaaaaa1 > a.txt
        ls
        
    - name: copying files
      uses: appleboy/scp-action@master
      with: 
        host: ${{ secrets.SJ_HOST }}
        username: ${{ secrets.SJ_USER }}
        password: ${{ secrets.SJ_PASSWORD }}
#        port: ${{ secrets.PORT }}
        source: "a.txt"
        target: "vpstest"
#        strip_components: 1







        
